void buildPrism(int m);
void buildTwistedPrism(int m);
void buildTAntiprism(int m);
void buildTBipyramid(int m);
void buildTrapezohedron(int m);
void buildRhombicDodecahedron();
void buildDeltoidalIcositetrahedron();
void buildRhombicTriancontahedron();
void buildDeltoidalHexecontahedron();
void buildTCuboctahedron();
void buildTIcosidodecahedron();
void buildCustomDiagram();
