double absolute(double x);
bool checkZero(point p);
void copyPoint(point a,point *b);
double dotProduct(point u,point v);
void crossProduct(point u,point v,point *w);
void rotateAroundAxis(point v,double angle,point *w);
void scale(point *v,double a);
double norm(point v);
double dist2(point a,point b);
double dist(point a,point b);
void normalize(point *v);
double angleU(point a,point b);
double angleCCW(point a,point b,point n);
double angleO(point o,point a,point b);
void normalVector(point a,point b,point *c);
void projectOnPlane(point *v,point n);
void sphereInterpR(point a,point b,double t,point *m);
void sphereInterpA(point a,point b,double t,point *m);
void intersectArcs(point p1,point p2,point q1,point q2,point *r1,point *r2);
